name       : perl-pango
version    : 1.227
release    : 7
source     :
    - https://netcologne.dl.sourceforge.net/project/gtk2-perl/Pango/1.227/Pango-1.227.tar.gz : 34b0a422df3fecd7597587048552457d48ae764c43bbefd2a9d62ceb6c8bac71
license    : LGPL-2.1-or-later
component  : programming.perl
summary    : Perl bindings for Pango
description: |
    Perl bindings for Pango
builddeps  :
    - pkgconfig(pango)
    - pkgconfig(cairo)
    - perl-cairo
    - perl-glib
    - perl-extutils-depends
    - perl-extutils-pkgconfig
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
